package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1



/**
 * Acceso generated by hbm2java
 */
public class Acceso  implements java.io.Serializable {


     private Integer idAcceso;
     private Funcionalidad funcionalidad;
     private Usuario usuario;

    public Acceso() {
    }

    public Acceso(Funcionalidad funcionalidad, Usuario usuario) {
       this.funcionalidad = funcionalidad;
       this.usuario = usuario;
    }
   
    public Integer getIdAcceso() {
        return this.idAcceso;
    }
    
    public void setIdAcceso(Integer idAcceso) {
        this.idAcceso = idAcceso;
    }
    public Funcionalidad getFuncionalidad() {
        return this.funcionalidad;
    }
    
    public void setFuncionalidad(Funcionalidad funcionalidad) {
        this.funcionalidad = funcionalidad;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


