package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private String codigoArticulo;
     private Subcategoriaarticulo subcategoriaarticulo;
     private Unidad unidad;
     private Usuario usuario;
     private String nombre;
     private String descripcion;
     private String fabricante;
     private Float cantidadMinima;
     private Float cantidadExistente;
     private String estadoArticulo;
     private BigDecimal precioVenta;
     private BigDecimal precioDocena;
     private BigDecimal precioEspecial;
     private byte[] imagen;
     private Set<Detallecotizacion> detallecotizacions = new HashSet<Detallecotizacion>(0);
     private Set<Detallepreventa> detallepreventas = new HashSet<Detallepreventa>(0);
     private Set<Salida> salidas = new HashSet<Salida>(0);
     private Set<Existencia> existencias = new HashSet<Existencia>(0);
     private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);
     private Set<Ubicacion> ubicacions = new HashSet<Ubicacion>(0);
     private Set<Devolucion> devolucions = new HashSet<Devolucion>(0);
     private Set<Entrada> entradas = new HashSet<Entrada>(0);
     private Set<Detalleventa> detalleventas = new HashSet<Detalleventa>(0);

    public Articulo() {
    }

	
    public Articulo(String codigoArticulo, Subcategoriaarticulo subcategoriaarticulo, Unidad unidad, Usuario usuario, String nombre, String estadoArticulo) {
        this.codigoArticulo = codigoArticulo;
        this.subcategoriaarticulo = subcategoriaarticulo;
        this.unidad = unidad;
        this.usuario = usuario;
        this.nombre = nombre;
        this.estadoArticulo = estadoArticulo;
    }
    public Articulo(String codigoArticulo, Subcategoriaarticulo subcategoriaarticulo, Unidad unidad, Usuario usuario, String nombre, String descripcion, String fabricante, Float cantidadMinima, Float cantidadExistente, String estadoArticulo, BigDecimal precioVenta, BigDecimal precioDocena, BigDecimal precioEspecial, byte[] imagen, Set<Detallecotizacion> detallecotizacions, Set<Detallepreventa> detallepreventas, Set<Salida> salidas, Set<Existencia> existencias, Set<Detallecompra> detallecompras, Set<Ubicacion> ubicacions, Set<Devolucion> devolucions, Set<Entrada> entradas, Set<Detalleventa> detalleventas) {
       this.codigoArticulo = codigoArticulo;
       this.subcategoriaarticulo = subcategoriaarticulo;
       this.unidad = unidad;
       this.usuario = usuario;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fabricante = fabricante;
       this.cantidadMinima = cantidadMinima;
       this.cantidadExistente = cantidadExistente;
       this.estadoArticulo = estadoArticulo;
       this.precioVenta = precioVenta;
       this.precioDocena = precioDocena;
       this.precioEspecial = precioEspecial;
       this.imagen = imagen;
       this.detallecotizacions = detallecotizacions;
       this.detallepreventas = detallepreventas;
       this.salidas = salidas;
       this.existencias = existencias;
       this.detallecompras = detallecompras;
       this.ubicacions = ubicacions;
       this.devolucions = devolucions;
       this.entradas = entradas;
       this.detalleventas = detalleventas;
    }
   
    public String getCodigoArticulo() {
        return this.codigoArticulo;
    }
    
    public void setCodigoArticulo(String codigoArticulo) {
        this.codigoArticulo = codigoArticulo;
    }
    public Subcategoriaarticulo getSubcategoriaarticulo() {
        return this.subcategoriaarticulo;
    }
    
    public void setSubcategoriaarticulo(Subcategoriaarticulo subcategoriaarticulo) {
        this.subcategoriaarticulo = subcategoriaarticulo;
    }
    public Unidad getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }
    public Float getCantidadMinima() {
        return this.cantidadMinima;
    }
    
    public void setCantidadMinima(Float cantidadMinima) {
        this.cantidadMinima = cantidadMinima;
    }
    public Float getCantidadExistente() {
        return this.cantidadExistente;
    }
    
    public void setCantidadExistente(Float cantidadExistente) {
        this.cantidadExistente = cantidadExistente;
    }
    public String getEstadoArticulo() {
        return this.estadoArticulo;
    }
    
    public void setEstadoArticulo(String estadoArticulo) {
        this.estadoArticulo = estadoArticulo;
    }
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }
    public BigDecimal getPrecioDocena() {
        return this.precioDocena;
    }
    
    public void setPrecioDocena(BigDecimal precioDocena) {
        this.precioDocena = precioDocena;
    }
    public BigDecimal getPrecioEspecial() {
        return this.precioEspecial;
    }
    
    public void setPrecioEspecial(BigDecimal precioEspecial) {
        this.precioEspecial = precioEspecial;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public Set<Detallecotizacion> getDetallecotizacions() {
        return this.detallecotizacions;
    }
    
    public void setDetallecotizacions(Set<Detallecotizacion> detallecotizacions) {
        this.detallecotizacions = detallecotizacions;
    }
    public Set<Detallepreventa> getDetallepreventas() {
        return this.detallepreventas;
    }
    
    public void setDetallepreventas(Set<Detallepreventa> detallepreventas) {
        this.detallepreventas = detallepreventas;
    }
    public Set<Salida> getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set<Salida> salidas) {
        this.salidas = salidas;
    }
    public Set<Existencia> getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(Set<Existencia> existencias) {
        this.existencias = existencias;
    }
    public Set<Detallecompra> getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set<Detallecompra> detallecompras) {
        this.detallecompras = detallecompras;
    }
    public Set<Ubicacion> getUbicacions() {
        return this.ubicacions;
    }
    
    public void setUbicacions(Set<Ubicacion> ubicacions) {
        this.ubicacions = ubicacions;
    }
    public Set<Devolucion> getDevolucions() {
        return this.devolucions;
    }
    
    public void setDevolucions(Set<Devolucion> devolucions) {
        this.devolucions = devolucions;
    }
    public Set<Entrada> getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set<Entrada> entradas) {
        this.entradas = entradas;
    }
    public Set<Detalleventa> getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set<Detalleventa> detalleventas) {
        this.detalleventas = detalleventas;
    }




}


