package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Banco generated by hbm2java
 */
public class Banco  implements java.io.Serializable {


     private Integer idBanco;
     private String nombreBanco;
     private Set<Cuentabancaria> cuentabancarias = new HashSet<Cuentabancaria>(0);

    public Banco() {
    }

	
    public Banco(String nombreBanco) {
        this.nombreBanco = nombreBanco;
    }
    public Banco(String nombreBanco, Set<Cuentabancaria> cuentabancarias) {
       this.nombreBanco = nombreBanco;
       this.cuentabancarias = cuentabancarias;
    }
   
    public Integer getIdBanco() {
        return this.idBanco;
    }
    
    public void setIdBanco(Integer idBanco) {
        this.idBanco = idBanco;
    }
    public String getNombreBanco() {
        return this.nombreBanco;
    }
    
    public void setNombreBanco(String nombreBanco) {
        this.nombreBanco = nombreBanco;
    }
    public Set<Cuentabancaria> getCuentabancarias() {
        return this.cuentabancarias;
    }
    
    public void setCuentabancarias(Set<Cuentabancaria> cuentabancarias) {
        this.cuentabancarias = cuentabancarias;
    }




}


