package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoriaarticulo generated by hbm2java
 */
public class Categoriaarticulo  implements java.io.Serializable {


     private Integer idCategoria;
     private String nombreCategoria;
     private Set<Subcategoriaarticulo> subcategoriaarticulos = new HashSet<Subcategoriaarticulo>(0);

    public Categoriaarticulo() {
    }

	
    public Categoriaarticulo(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public Categoriaarticulo(String nombreCategoria, Set<Subcategoriaarticulo> subcategoriaarticulos) {
       this.nombreCategoria = nombreCategoria;
       this.subcategoriaarticulos = subcategoriaarticulos;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public Set<Subcategoriaarticulo> getSubcategoriaarticulos() {
        return this.subcategoriaarticulos;
    }
    
    public void setSubcategoriaarticulos(Set<Subcategoriaarticulo> subcategoriaarticulos) {
        this.subcategoriaarticulos = subcategoriaarticulos;
    }




}


