package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private Integer idCiudad;
     private Pais pais;
     private String nombreCiudad;
     private Set<Contacto> contactos = new HashSet<Contacto>(0);
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);

    public Ciudad() {
    }

	
    public Ciudad(Pais pais, String nombreCiudad) {
        this.pais = pais;
        this.nombreCiudad = nombreCiudad;
    }
    public Ciudad(Pais pais, String nombreCiudad, Set<Contacto> contactos, Set<Proveedor> proveedors) {
       this.pais = pais;
       this.nombreCiudad = nombreCiudad;
       this.contactos = contactos;
       this.proveedors = proveedors;
    }
   
    public Integer getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(Integer idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombreCiudad() {
        return this.nombreCiudad;
    }
    
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }
    public Set<Contacto> getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set<Contacto> contactos) {
        this.contactos = contactos;
    }
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }




}


