package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String ciCliente;
     private String nombresCliente;
     private String direccion;
     private String telefono;
     private String celular;
     private String correoElectronico;
     private String estado;
     private Set<Preventa> preventas = new HashSet<Preventa>(0);
     private Set<Cotizacion> cotizacions = new HashSet<Cotizacion>(0);
     private Set<Ventaservicio> ventaservicios = new HashSet<Ventaservicio>(0);
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Cliente() {
    }

	
    public Cliente(String ciCliente, String nombresCliente) {
        this.ciCliente = ciCliente;
        this.nombresCliente = nombresCliente;
    }
    public Cliente(String ciCliente, String nombresCliente, String direccion, String telefono, String celular, String correoElectronico, String estado, Set<Preventa> preventas, Set<Cotizacion> cotizacions, Set<Ventaservicio> ventaservicios, Set<Venta> ventas) {
       this.ciCliente = ciCliente;
       this.nombresCliente = nombresCliente;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.correoElectronico = correoElectronico;
       this.estado = estado;
       this.preventas = preventas;
       this.cotizacions = cotizacions;
       this.ventaservicios = ventaservicios;
       this.ventas = ventas;
    }
   
    public String getCiCliente() {
        return this.ciCliente;
    }
    
    public void setCiCliente(String ciCliente) {
        this.ciCliente = ciCliente;
    }
    public String getNombresCliente() {
        return this.nombresCliente;
    }
    
    public void setNombresCliente(String nombresCliente) {
        this.nombresCliente = nombresCliente;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Preventa> getPreventas() {
        return this.preventas;
    }
    
    public void setPreventas(Set<Preventa> preventas) {
        this.preventas = preventas;
    }
    public Set<Cotizacion> getCotizacions() {
        return this.cotizacions;
    }
    
    public void setCotizacions(Set<Cotizacion> cotizacions) {
        this.cotizacions = cotizacions;
    }
    public Set<Ventaservicio> getVentaservicios() {
        return this.ventaservicios;
    }
    
    public void setVentaservicios(Set<Ventaservicio> ventaservicios) {
        this.ventaservicios = ventaservicios;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


