package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private Almacen almacen;
     private Proveedor proveedor;
     private Tipomoneda tipomoneda;
     private Tipopago tipopago;
     private Usuario usuario;
     private BigDecimal tipoCambio;
     private String facturaCompra;
     private String numeroRecibo;
     private Date fechaCompra;
     private String observacionCompra;
     private BigDecimal montoCompra;
     private String estado;
     private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);
     private Set<Cronocomprascred> cronocomprascreds = new HashSet<Cronocomprascred>(0);

    public Compra() {
    }

	
    public Compra(Proveedor proveedor, Tipomoneda tipomoneda, Tipopago tipopago, Usuario usuario, BigDecimal tipoCambio, Date fechaCompra) {
        this.proveedor = proveedor;
        this.tipomoneda = tipomoneda;
        this.tipopago = tipopago;
        this.usuario = usuario;
        this.tipoCambio = tipoCambio;
        this.fechaCompra = fechaCompra;
    }
    public Compra(Almacen almacen, Proveedor proveedor, Tipomoneda tipomoneda, Tipopago tipopago, Usuario usuario, BigDecimal tipoCambio, String facturaCompra, String numeroRecibo, Date fechaCompra, String observacionCompra, BigDecimal montoCompra, String estado, Set<Detallecompra> detallecompras, Set<Cronocomprascred> cronocomprascreds) {
       this.almacen = almacen;
       this.proveedor = proveedor;
       this.tipomoneda = tipomoneda;
       this.tipopago = tipopago;
       this.usuario = usuario;
       this.tipoCambio = tipoCambio;
       this.facturaCompra = facturaCompra;
       this.numeroRecibo = numeroRecibo;
       this.fechaCompra = fechaCompra;
       this.observacionCompra = observacionCompra;
       this.montoCompra = montoCompra;
       this.estado = estado;
       this.detallecompras = detallecompras;
       this.cronocomprascreds = cronocomprascreds;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Tipomoneda getTipomoneda() {
        return this.tipomoneda;
    }
    
    public void setTipomoneda(Tipomoneda tipomoneda) {
        this.tipomoneda = tipomoneda;
    }
    public Tipopago getTipopago() {
        return this.tipopago;
    }
    
    public void setTipopago(Tipopago tipopago) {
        this.tipopago = tipopago;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
    public String getFacturaCompra() {
        return this.facturaCompra;
    }
    
    public void setFacturaCompra(String facturaCompra) {
        this.facturaCompra = facturaCompra;
    }
    public String getNumeroRecibo() {
        return this.numeroRecibo;
    }
    
    public void setNumeroRecibo(String numeroRecibo) {
        this.numeroRecibo = numeroRecibo;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public String getObservacionCompra() {
        return this.observacionCompra;
    }
    
    public void setObservacionCompra(String observacionCompra) {
        this.observacionCompra = observacionCompra;
    }
    public BigDecimal getMontoCompra() {
        return this.montoCompra;
    }
    
    public void setMontoCompra(BigDecimal montoCompra) {
        this.montoCompra = montoCompra;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Detallecompra> getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set<Detallecompra> detallecompras) {
        this.detallecompras = detallecompras;
    }
    public Set<Cronocomprascred> getCronocomprascreds() {
        return this.cronocomprascreds;
    }
    
    public void setCronocomprascreds(Set<Cronocomprascred> cronocomprascreds) {
        this.cronocomprascreds = cronocomprascreds;
    }




}


