package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1



/**
 * Contacto generated by hbm2java
 */
public class Contacto  implements java.io.Serializable {


     private Integer idContacto;
     private Ciudad ciudad;
     private Proveedor proveedor;
     private String nombreCompleto;
     private String direccion;
     private String telefono;
     private String celular;
     private String correoElectronico;
     private String cargo;

    public Contacto() {
    }

	
    public Contacto(Ciudad ciudad, Proveedor proveedor) {
        this.ciudad = ciudad;
        this.proveedor = proveedor;
    }
    public Contacto(Ciudad ciudad, Proveedor proveedor, String nombreCompleto, String direccion, String telefono, String celular, String correoElectronico, String cargo) {
       this.ciudad = ciudad;
       this.proveedor = proveedor;
       this.nombreCompleto = nombreCompleto;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.correoElectronico = correoElectronico;
       this.cargo = cargo;
    }
   
    public Integer getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(Integer idContacto) {
        this.idContacto = idContacto;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }




}


