package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cotizacion generated by hbm2java
 */
public class Cotizacion  implements java.io.Serializable {


     private Integer numeroCotizacion;
     private Cliente cliente;
     private Usuario usuario;
     private Date fechaCotizacion;
     private BigDecimal montoTotal;
     private BigDecimal tipoCambio;
     private String observaciones;
     private int idTipomoneda;
     private String estado;
     private String vigencia;
     private Set<Detallecotizacion> detallecotizacions = new HashSet<Detallecotizacion>(0);

    public Cotizacion() {
    }

	
    public Cotizacion(Cliente cliente, Usuario usuario, Date fechaCotizacion, BigDecimal montoTotal, int idTipomoneda) {
        this.cliente = cliente;
        this.usuario = usuario;
        this.fechaCotizacion = fechaCotizacion;
        this.montoTotal = montoTotal;
        this.idTipomoneda = idTipomoneda;
    }
    public Cotizacion(Cliente cliente, Usuario usuario, Date fechaCotizacion, BigDecimal montoTotal, BigDecimal tipoCambio, String observaciones, int idTipomoneda, String estado, String vigencia, Set<Detallecotizacion> detallecotizacions) {
       this.cliente = cliente;
       this.usuario = usuario;
       this.fechaCotizacion = fechaCotizacion;
       this.montoTotal = montoTotal;
       this.tipoCambio = tipoCambio;
       this.observaciones = observaciones;
       this.idTipomoneda = idTipomoneda;
       this.estado = estado;
       this.vigencia = vigencia;
       this.detallecotizacions = detallecotizacions;
    }
   
    public Integer getNumeroCotizacion() {
        return this.numeroCotizacion;
    }
    
    public void setNumeroCotizacion(Integer numeroCotizacion) {
        this.numeroCotizacion = numeroCotizacion;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCotizacion() {
        return this.fechaCotizacion;
    }
    
    public void setFechaCotizacion(Date fechaCotizacion) {
        this.fechaCotizacion = fechaCotizacion;
    }
    public BigDecimal getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(BigDecimal montoTotal) {
        this.montoTotal = montoTotal;
    }
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public int getIdTipomoneda() {
        return this.idTipomoneda;
    }
    
    public void setIdTipomoneda(int idTipomoneda) {
        this.idTipomoneda = idTipomoneda;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getVigencia() {
        return this.vigencia;
    }
    
    public void setVigencia(String vigencia) {
        this.vigencia = vigencia;
    }
    public Set<Detallecotizacion> getDetallecotizacions() {
        return this.detallecotizacions;
    }
    
    public void setDetallecotizacions(Set<Detallecotizacion> detallecotizacions) {
        this.detallecotizacions = detallecotizacions;
    }




}


