package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cronoventascredito generated by hbm2java
 */
public class Cronoventascredito  implements java.io.Serializable {


     private Integer idCronoV;
     private Usuario usuario;
     private Venta venta;
     private Date fechaProgramada;
     private Date fechaHoraRegistro;
     private Set<Pagoventascredito> pagoventascreditos = new HashSet<Pagoventascredito>(0);

    public Cronoventascredito() {
    }

	
    public Cronoventascredito(Usuario usuario, Venta venta, Date fechaProgramada) {
        this.usuario = usuario;
        this.venta = venta;
        this.fechaProgramada = fechaProgramada;
    }
    public Cronoventascredito(Usuario usuario, Venta venta, Date fechaProgramada, Date fechaHoraRegistro, Set<Pagoventascredito> pagoventascreditos) {
       this.usuario = usuario;
       this.venta = venta;
       this.fechaProgramada = fechaProgramada;
       this.fechaHoraRegistro = fechaHoraRegistro;
       this.pagoventascreditos = pagoventascreditos;
    }
   
    public Integer getIdCronoV() {
        return this.idCronoV;
    }
    
    public void setIdCronoV(Integer idCronoV) {
        this.idCronoV = idCronoV;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Date getFechaProgramada() {
        return this.fechaProgramada;
    }
    
    public void setFechaProgramada(Date fechaProgramada) {
        this.fechaProgramada = fechaProgramada;
    }
    public Date getFechaHoraRegistro() {
        return this.fechaHoraRegistro;
    }
    
    public void setFechaHoraRegistro(Date fechaHoraRegistro) {
        this.fechaHoraRegistro = fechaHoraRegistro;
    }
    public Set<Pagoventascredito> getPagoventascreditos() {
        return this.pagoventascreditos;
    }
    
    public void setPagoventascreditos(Set<Pagoventascredito> pagoventascreditos) {
        this.pagoventascreditos = pagoventascreditos;
    }




}


