package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cronocomprascred generated by hbm2java
 */
public class Cronocomprascred  implements java.io.Serializable {


     private Integer idCronogramaC;
     private Compra compra;
     private Usuario usuario;
     private Date fechaProgramada;
     private Date fechaHoraRegistro;
     private Set<Pagocompracredito> pagocompracreditos = new HashSet<Pagocompracredito>(0);

    public Cronocomprascred() {
    }

	
    public Cronocomprascred(Compra compra, Usuario usuario, Date fechaProgramada) {
        this.compra = compra;
        this.usuario = usuario;
        this.fechaProgramada = fechaProgramada;
    }
    public Cronocomprascred(Compra compra, Usuario usuario, Date fechaProgramada, Date fechaHoraRegistro, Set<Pagocompracredito> pagocompracreditos) {
       this.compra = compra;
       this.usuario = usuario;
       this.fechaProgramada = fechaProgramada;
       this.fechaHoraRegistro = fechaHoraRegistro;
       this.pagocompracreditos = pagocompracreditos;
    }
   
    public Integer getIdCronogramaC() {
        return this.idCronogramaC;
    }
    
    public void setIdCronogramaC(Integer idCronogramaC) {
        this.idCronogramaC = idCronogramaC;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaProgramada() {
        return this.fechaProgramada;
    }
    
    public void setFechaProgramada(Date fechaProgramada) {
        this.fechaProgramada = fechaProgramada;
    }
    public Date getFechaHoraRegistro() {
        return this.fechaHoraRegistro;
    }
    
    public void setFechaHoraRegistro(Date fechaHoraRegistro) {
        this.fechaHoraRegistro = fechaHoraRegistro;
    }
    public Set<Pagocompracredito> getPagocompracreditos() {
        return this.pagocompracreditos;
    }
    
    public void setPagocompracreditos(Set<Pagocompracredito> pagocompracreditos) {
        this.pagocompracreditos = pagocompracreditos;
    }




}


