package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1



/**
 * Cuentabancaria generated by hbm2java
 */
public class Cuentabancaria  implements java.io.Serializable {


     private Integer idCuentabancaria;
     private Banco banco;
     private Proveedor proveedor;
     private Tipomoneda tipomoneda;
     private String numeroCuenta;

    public Cuentabancaria() {
    }

    public Cuentabancaria(Banco banco, Proveedor proveedor, Tipomoneda tipomoneda, String numeroCuenta) {
       this.banco = banco;
       this.proveedor = proveedor;
       this.tipomoneda = tipomoneda;
       this.numeroCuenta = numeroCuenta;
    }
   
    public Integer getIdCuentabancaria() {
        return this.idCuentabancaria;
    }
    
    public void setIdCuentabancaria(Integer idCuentabancaria) {
        this.idCuentabancaria = idCuentabancaria;
    }
    public Banco getBanco() {
        return this.banco;
    }
    
    public void setBanco(Banco banco) {
        this.banco = banco;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Tipomoneda getTipomoneda() {
        return this.tipomoneda;
    }
    
    public void setTipomoneda(Tipomoneda tipomoneda) {
        this.tipomoneda = tipomoneda;
    }
    public String getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(String numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }




}


