package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detallecotizacion generated by hbm2java
 */
public class Detallecotizacion  implements java.io.Serializable {


     private Integer idDetalleCotizacion;
     private Articulo articulo;
     private Cotizacion cotizacion;
     private float cantidad;
     private BigDecimal precio;
     private BigDecimal monto;

    public Detallecotizacion() {
    }

    public Detallecotizacion(Articulo articulo, Cotizacion cotizacion, float cantidad, BigDecimal precio, BigDecimal monto) {
       this.articulo = articulo;
       this.cotizacion = cotizacion;
       this.cantidad = cantidad;
       this.precio = precio;
       this.monto = monto;
    }
   
    public Integer getIdDetalleCotizacion() {
        return this.idDetalleCotizacion;
    }
    
    public void setIdDetalleCotizacion(Integer idDetalleCotizacion) {
        this.idDetalleCotizacion = idDetalleCotizacion;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Cotizacion getCotizacion() {
        return this.cotizacion;
    }
    
    public void setCotizacion(Cotizacion cotizacion) {
        this.cotizacion = cotizacion;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }




}


