package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detallecompra generated by hbm2java
 */
public class Detallecompra  implements java.io.Serializable {


     private Integer idDetalleCompra;
     private Articulo articulo;
     private Compra compra;
     private float cantidad;
     private BigDecimal costoUnitario;
     private BigDecimal costoTotal;

    public Detallecompra() {
    }

    public Detallecompra(Articulo articulo, Compra compra, float cantidad, BigDecimal costoUnitario, BigDecimal costoTotal) {
       this.articulo = articulo;
       this.compra = compra;
       this.cantidad = cantidad;
       this.costoUnitario = costoUnitario;
       this.costoTotal = costoTotal;
    }
   
    public Integer getIdDetalleCompra() {
        return this.idDetalleCompra;
    }
    
    public void setIdDetalleCompra(Integer idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getCostoUnitario() {
        return this.costoUnitario;
    }
    
    public void setCostoUnitario(BigDecimal costoUnitario) {
        this.costoUnitario = costoUnitario;
    }
    public BigDecimal getCostoTotal() {
        return this.costoTotal;
    }
    
    public void setCostoTotal(BigDecimal costoTotal) {
        this.costoTotal = costoTotal;
    }




}


