package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detallefacturaanulada generated by hbm2java
 */
public class Detallefacturaanulada  implements java.io.Serializable {


     private Integer idDetalleFacturaAnulada;
     private Integer numeroVenta;
     private String codigoArticulo;
     private BigDecimal precioVentaReal;
     private Float cantidad;
     private BigDecimal total;
     private Integer idFactura;

    public Detallefacturaanulada() {
    }

    public Detallefacturaanulada(Integer numeroVenta, String codigoArticulo, BigDecimal precioVentaReal, Float cantidad, BigDecimal total, Integer idFactura) {
       this.numeroVenta = numeroVenta;
       this.codigoArticulo = codigoArticulo;
       this.precioVentaReal = precioVentaReal;
       this.cantidad = cantidad;
       this.total = total;
       this.idFactura = idFactura;
    }
   
    public Integer getIdDetalleFacturaAnulada() {
        return this.idDetalleFacturaAnulada;
    }
    
    public void setIdDetalleFacturaAnulada(Integer idDetalleFacturaAnulada) {
        this.idDetalleFacturaAnulada = idDetalleFacturaAnulada;
    }
    public Integer getNumeroVenta() {
        return this.numeroVenta;
    }
    
    public void setNumeroVenta(Integer numeroVenta) {
        this.numeroVenta = numeroVenta;
    }
    public String getCodigoArticulo() {
        return this.codigoArticulo;
    }
    
    public void setCodigoArticulo(String codigoArticulo) {
        this.codigoArticulo = codigoArticulo;
    }
    public BigDecimal getPrecioVentaReal() {
        return this.precioVentaReal;
    }
    
    public void setPrecioVentaReal(BigDecimal precioVentaReal) {
        this.precioVentaReal = precioVentaReal;
    }
    public Float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Float cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }




}


