package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Devolucion generated by hbm2java
 */
public class Devolucion  implements java.io.Serializable {


     private Integer idDevolucion;
     private Articulo articulo;
     private Venta venta;
     private BigDecimal precioVentaReal;
     private float cantidad;
     private BigDecimal total;
     private Integer idFactura;
     private String estadoArticulo;
     private Date fechaDevolucion;
     private String observacion;

    public Devolucion() {
    }

	
    public Devolucion(Articulo articulo, Venta venta, BigDecimal precioVentaReal, float cantidad, BigDecimal total, Date fechaDevolucion) {
        this.articulo = articulo;
        this.venta = venta;
        this.precioVentaReal = precioVentaReal;
        this.cantidad = cantidad;
        this.total = total;
        this.fechaDevolucion = fechaDevolucion;
    }
    public Devolucion(Articulo articulo, Venta venta, BigDecimal precioVentaReal, float cantidad, BigDecimal total, Integer idFactura, String estadoArticulo, Date fechaDevolucion, String observacion) {
       this.articulo = articulo;
       this.venta = venta;
       this.precioVentaReal = precioVentaReal;
       this.cantidad = cantidad;
       this.total = total;
       this.idFactura = idFactura;
       this.estadoArticulo = estadoArticulo;
       this.fechaDevolucion = fechaDevolucion;
       this.observacion = observacion;
    }
   
    public Integer getIdDevolucion() {
        return this.idDevolucion;
    }
    
    public void setIdDevolucion(Integer idDevolucion) {
        this.idDevolucion = idDevolucion;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public BigDecimal getPrecioVentaReal() {
        return this.precioVentaReal;
    }
    
    public void setPrecioVentaReal(BigDecimal precioVentaReal) {
        this.precioVentaReal = precioVentaReal;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public String getEstadoArticulo() {
        return this.estadoArticulo;
    }
    
    public void setEstadoArticulo(String estadoArticulo) {
        this.estadoArticulo = estadoArticulo;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


