package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private String ciEmpleado;
     private String nombresEmpleado;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String direccion;
     private String telefono;
     private String celular;
     private String estado;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Ingreso> ingresos = new HashSet<Ingreso>(0);

    public Empleado() {
    }

	
    public Empleado(String nombresEmpleado, String apellidoPaterno) {
        this.nombresEmpleado = nombresEmpleado;
        this.apellidoPaterno = apellidoPaterno;
    }
    public Empleado(String ciEmpleado, String nombresEmpleado, String apellidoPaterno, String apellidoMaterno, String direccion, String telefono, String celular, String estado, Set<Usuario> usuarios, Set<Ingreso> ingresos) {
       this.ciEmpleado = ciEmpleado;
       this.nombresEmpleado = nombresEmpleado;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.estado = estado;
       this.usuarios = usuarios;
       this.ingresos = ingresos;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getCiEmpleado() {
        return this.ciEmpleado;
    }
    
    public void setCiEmpleado(String ciEmpleado) {
        this.ciEmpleado = ciEmpleado;
    }
    public String getNombresEmpleado() {
        return this.nombresEmpleado;
    }
    
    public void setNombresEmpleado(String nombresEmpleado) {
        this.nombresEmpleado = nombresEmpleado;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Ingreso> getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set<Ingreso> ingresos) {
        this.ingresos = ingresos;
    }




}


