package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Entrada generated by hbm2java
 */
public class Entrada  implements java.io.Serializable {


     private Integer idEntrada;
     private Articulo articulo;
     private float cantidad;
     private Date fechaEntrada;
     private String observacion;

    public Entrada() {
    }

	
    public Entrada(Articulo articulo, float cantidad, Date fechaEntrada) {
        this.articulo = articulo;
        this.cantidad = cantidad;
        this.fechaEntrada = fechaEntrada;
    }
    public Entrada(Articulo articulo, float cantidad, Date fechaEntrada, String observacion) {
       this.articulo = articulo;
       this.cantidad = cantidad;
       this.fechaEntrada = fechaEntrada;
       this.observacion = observacion;
    }
   
    public Integer getIdEntrada() {
        return this.idEntrada;
    }
    
    public void setIdEntrada(Integer idEntrada) {
        this.idEntrada = idEntrada;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFechaEntrada() {
        return this.fechaEntrada;
    }
    
    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


