package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estante generated by hbm2java
 */
public class Estante  implements java.io.Serializable {


     private String codigoEstante;
     private Almacen almacen;
     private String descripcion;
     private byte numeroFilas;
     private byte numeroColumnas;
     private String estadoEstante;
     private Set<Ubicacion> ubicacions = new HashSet<Ubicacion>(0);

    public Estante() {
    }

	
    public Estante(String codigoEstante, Almacen almacen, byte numeroFilas, byte numeroColumnas) {
        this.codigoEstante = codigoEstante;
        this.almacen = almacen;
        this.numeroFilas = numeroFilas;
        this.numeroColumnas = numeroColumnas;
    }
    public Estante(String codigoEstante, Almacen almacen, String descripcion, byte numeroFilas, byte numeroColumnas, String estadoEstante, Set<Ubicacion> ubicacions) {
       this.codigoEstante = codigoEstante;
       this.almacen = almacen;
       this.descripcion = descripcion;
       this.numeroFilas = numeroFilas;
       this.numeroColumnas = numeroColumnas;
       this.estadoEstante = estadoEstante;
       this.ubicacions = ubicacions;
    }
   
    public String getCodigoEstante() {
        return this.codigoEstante;
    }
    
    public void setCodigoEstante(String codigoEstante) {
        this.codigoEstante = codigoEstante;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public byte getNumeroFilas() {
        return this.numeroFilas;
    }
    
    public void setNumeroFilas(byte numeroFilas) {
        this.numeroFilas = numeroFilas;
    }
    public byte getNumeroColumnas() {
        return this.numeroColumnas;
    }
    
    public void setNumeroColumnas(byte numeroColumnas) {
        this.numeroColumnas = numeroColumnas;
    }
    public String getEstadoEstante() {
        return this.estadoEstante;
    }
    
    public void setEstadoEstante(String estadoEstante) {
        this.estadoEstante = estadoEstante;
    }
    public Set<Ubicacion> getUbicacions() {
        return this.ubicacions;
    }
    
    public void setUbicacions(Set<Ubicacion> ubicacions) {
        this.ubicacions = ubicacions;
    }




}


