package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1



/**
 * Existencia generated by hbm2java
 */
public class Existencia  implements java.io.Serializable {


     private Integer idExistencia;
     private Almacen almacen;
     private Articulo articulo;
     private float cantidad;

    public Existencia() {
    }

    public Existencia(Almacen almacen, Articulo articulo, float cantidad) {
       this.almacen = almacen;
       this.articulo = articulo;
       this.cantidad = cantidad;
    }
   
    public Integer getIdExistencia() {
        return this.idExistencia;
    }
    
    public void setIdExistencia(Integer idExistencia) {
        this.idExistencia = idExistencia;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }




}


