package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private int numeroFactura;
     private String numeroAutorizacion;
     private Date fechaFactura;
     private String nitCliente;
     private String razonSocial;
     private BigDecimal monto;
     private String codigoControl;
     private String estado;
     private Long tiempoRegistro;
     private Set<Preventafactura> preventafacturas = new HashSet<Preventafactura>(0);
     private Set<Ventafactura> ventafacturas = new HashSet<Ventafactura>(0);

    public Factura() {
    }

	
    public Factura(int numeroFactura, String numeroAutorizacion, Date fechaFactura, String nitCliente, String razonSocial, BigDecimal monto, String codigoControl, String estado) {
        this.numeroFactura = numeroFactura;
        this.numeroAutorizacion = numeroAutorizacion;
        this.fechaFactura = fechaFactura;
        this.nitCliente = nitCliente;
        this.razonSocial = razonSocial;
        this.monto = monto;
        this.codigoControl = codigoControl;
        this.estado = estado;
    }
    public Factura(int numeroFactura, String numeroAutorizacion, Date fechaFactura, String nitCliente, String razonSocial, BigDecimal monto, String codigoControl, String estado, Long tiempoRegistro, Set<Preventafactura> preventafacturas, Set<Ventafactura> ventafacturas) {
       this.numeroFactura = numeroFactura;
       this.numeroAutorizacion = numeroAutorizacion;
       this.fechaFactura = fechaFactura;
       this.nitCliente = nitCliente;
       this.razonSocial = razonSocial;
       this.monto = monto;
       this.codigoControl = codigoControl;
       this.estado = estado;
       this.tiempoRegistro = tiempoRegistro;
       this.preventafacturas = preventafacturas;
       this.ventafacturas = ventafacturas;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public int getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(int numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public String getNumeroAutorizacion() {
        return this.numeroAutorizacion;
    }
    
    public void setNumeroAutorizacion(String numeroAutorizacion) {
        this.numeroAutorizacion = numeroAutorizacion;
    }
    public Date getFechaFactura() {
        return this.fechaFactura;
    }
    
    public void setFechaFactura(Date fechaFactura) {
        this.fechaFactura = fechaFactura;
    }
    public String getNitCliente() {
        return this.nitCliente;
    }
    
    public void setNitCliente(String nitCliente) {
        this.nitCliente = nitCliente;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public String getCodigoControl() {
        return this.codigoControl;
    }
    
    public void setCodigoControl(String codigoControl) {
        this.codigoControl = codigoControl;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Long getTiempoRegistro() {
        return this.tiempoRegistro;
    }
    
    public void setTiempoRegistro(Long tiempoRegistro) {
        this.tiempoRegistro = tiempoRegistro;
    }
    public Set<Preventafactura> getPreventafacturas() {
        return this.preventafacturas;
    }
    
    public void setPreventafacturas(Set<Preventafactura> preventafacturas) {
        this.preventafacturas = preventafacturas;
    }
    public Set<Ventafactura> getVentafacturas() {
        return this.ventafacturas;
    }
    
    public void setVentafacturas(Set<Ventafactura> ventafacturas) {
        this.ventafacturas = ventafacturas;
    }




}


