package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionalidad generated by hbm2java
 */
public class Funcionalidad  implements java.io.Serializable {


     private Integer idFuncionalidad;
     private String nombre;
     private Set<Acceso> accesos = new HashSet<Acceso>(0);

    public Funcionalidad() {
    }

	
    public Funcionalidad(String nombre) {
        this.nombre = nombre;
    }
    public Funcionalidad(String nombre, Set<Acceso> accesos) {
       this.nombre = nombre;
       this.accesos = accesos;
    }
   
    public Integer getIdFuncionalidad() {
        return this.idFuncionalidad;
    }
    
    public void setIdFuncionalidad(Integer idFuncionalidad) {
        this.idFuncionalidad = idFuncionalidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Acceso> getAccesos() {
        return this.accesos;
    }
    
    public void setAccesos(Set<Acceso> accesos) {
        this.accesos = accesos;
    }




}


