package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Gasto generated by hbm2java
 */
public class Gasto  implements java.io.Serializable {


     private Integer idGasto;
     private Usuario usuario;
     private String concepto;
     private String detalle;
     private BigDecimal monto;
     private Date fechaHoraRegistro;

    public Gasto() {
    }

	
    public Gasto(Usuario usuario, String concepto, BigDecimal monto) {
        this.usuario = usuario;
        this.concepto = concepto;
        this.monto = monto;
    }
    public Gasto(Usuario usuario, String concepto, String detalle, BigDecimal monto, Date fechaHoraRegistro) {
       this.usuario = usuario;
       this.concepto = concepto;
       this.detalle = detalle;
       this.monto = monto;
       this.fechaHoraRegistro = fechaHoraRegistro;
    }
   
    public Integer getIdGasto() {
        return this.idGasto;
    }
    
    public void setIdGasto(Integer idGasto) {
        this.idGasto = idGasto;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Date getFechaHoraRegistro() {
        return this.fechaHoraRegistro;
    }
    
    public void setFechaHoraRegistro(Date fechaHoraRegistro) {
        this.fechaHoraRegistro = fechaHoraRegistro;
    }




}


