package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Pagocompracredito generated by hbm2java
 */
public class Pagocompracredito  implements java.io.Serializable {


     private Integer idPagocredito;
     private Cronocomprascred cronocomprascred;
     private Usuario usuario;
     private BigDecimal montoPagado;
     private Date fechaPago;
     private BigDecimal saldo;
     private String observacion;

    public Pagocompracredito() {
    }

	
    public Pagocompracredito(Cronocomprascred cronocomprascred, Usuario usuario, BigDecimal montoPagado, Date fechaPago, BigDecimal saldo) {
        this.cronocomprascred = cronocomprascred;
        this.usuario = usuario;
        this.montoPagado = montoPagado;
        this.fechaPago = fechaPago;
        this.saldo = saldo;
    }
    public Pagocompracredito(Cronocomprascred cronocomprascred, Usuario usuario, BigDecimal montoPagado, Date fechaPago, BigDecimal saldo, String observacion) {
       this.cronocomprascred = cronocomprascred;
       this.usuario = usuario;
       this.montoPagado = montoPagado;
       this.fechaPago = fechaPago;
       this.saldo = saldo;
       this.observacion = observacion;
    }
   
    public Integer getIdPagocredito() {
        return this.idPagocredito;
    }
    
    public void setIdPagocredito(Integer idPagocredito) {
        this.idPagocredito = idPagocredito;
    }
    public Cronocomprascred getCronocomprascred() {
        return this.cronocomprascred;
    }
    
    public void setCronocomprascred(Cronocomprascred cronocomprascred) {
        this.cronocomprascred = cronocomprascred;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getMontoPagado() {
        return this.montoPagado;
    }
    
    public void setMontoPagado(BigDecimal montoPagado) {
        this.montoPagado = montoPagado;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public BigDecimal getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(BigDecimal saldo) {
        this.saldo = saldo;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


