package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Preventa generated by hbm2java
 */
public class Preventa  implements java.io.Serializable {


     private Integer numeroPreVenta;
     private Almacen almacen;
     private Cliente cliente;
     private Tipomoneda tipomoneda;
     private Tipopago tipopago;
     private Usuario usuario;
     private Long tiempoRegistro;
     private Date fechaPreVenta;
     private BigDecimal montoTotal;
     private BigDecimal tipoCambio;
     private Double impuesto;
     private String observaciones;
     private String estado;
     private Date fechaHoraRegistro;
     private Set<Preventafactura> preventafacturas = new HashSet<Preventafactura>(0);
     private Set<Detallepreventa> detallepreventas = new HashSet<Detallepreventa>(0);

    public Preventa() {
    }

	
    public Preventa(Cliente cliente, Tipomoneda tipomoneda, Tipopago tipopago, Usuario usuario, Date fechaPreVenta) {
        this.cliente = cliente;
        this.tipomoneda = tipomoneda;
        this.tipopago = tipopago;
        this.usuario = usuario;
        this.fechaPreVenta = fechaPreVenta;
    }
    public Preventa(Almacen almacen, Cliente cliente, Tipomoneda tipomoneda, Tipopago tipopago, Usuario usuario, Long tiempoRegistro, Date fechaPreVenta, BigDecimal montoTotal, BigDecimal tipoCambio, Double impuesto, String observaciones, String estado, Date fechaHoraRegistro, Set<Preventafactura> preventafacturas, Set<Detallepreventa> detallepreventas) {
       this.almacen = almacen;
       this.cliente = cliente;
       this.tipomoneda = tipomoneda;
       this.tipopago = tipopago;
       this.usuario = usuario;
       this.tiempoRegistro = tiempoRegistro;
       this.fechaPreVenta = fechaPreVenta;
       this.montoTotal = montoTotal;
       this.tipoCambio = tipoCambio;
       this.impuesto = impuesto;
       this.observaciones = observaciones;
       this.estado = estado;
       this.fechaHoraRegistro = fechaHoraRegistro;
       this.preventafacturas = preventafacturas;
       this.detallepreventas = detallepreventas;
    }
   
    public Integer getNumeroPreVenta() {
        return this.numeroPreVenta;
    }
    
    public void setNumeroPreVenta(Integer numeroPreVenta) {
        this.numeroPreVenta = numeroPreVenta;
    }
    public Almacen getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(Almacen almacen) {
        this.almacen = almacen;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Tipomoneda getTipomoneda() {
        return this.tipomoneda;
    }
    
    public void setTipomoneda(Tipomoneda tipomoneda) {
        this.tipomoneda = tipomoneda;
    }
    public Tipopago getTipopago() {
        return this.tipopago;
    }
    
    public void setTipopago(Tipopago tipopago) {
        this.tipopago = tipopago;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Long getTiempoRegistro() {
        return this.tiempoRegistro;
    }
    
    public void setTiempoRegistro(Long tiempoRegistro) {
        this.tiempoRegistro = tiempoRegistro;
    }
    public Date getFechaPreVenta() {
        return this.fechaPreVenta;
    }
    
    public void setFechaPreVenta(Date fechaPreVenta) {
        this.fechaPreVenta = fechaPreVenta;
    }
    public BigDecimal getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(BigDecimal montoTotal) {
        this.montoTotal = montoTotal;
    }
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
    public Double getImpuesto() {
        return this.impuesto;
    }
    
    public void setImpuesto(Double impuesto) {
        this.impuesto = impuesto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaHoraRegistro() {
        return this.fechaHoraRegistro;
    }
    
    public void setFechaHoraRegistro(Date fechaHoraRegistro) {
        this.fechaHoraRegistro = fechaHoraRegistro;
    }
    public Set<Preventafactura> getPreventafacturas() {
        return this.preventafacturas;
    }
    
    public void setPreventafacturas(Set<Preventafactura> preventafacturas) {
        this.preventafacturas = preventafacturas;
    }
    public Set<Detallepreventa> getDetallepreventas() {
        return this.detallepreventas;
    }
    
    public void setDetallepreventas(Set<Detallepreventa> detallepreventas) {
        this.detallepreventas = detallepreventas;
    }




}


