package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1



/**
 * Preventafactura generated by hbm2java
 */
public class Preventafactura  implements java.io.Serializable {


     private Integer idPreventaFactura;
     private Factura factura;
     private Preventa preventa;

    public Preventafactura() {
    }

    public Preventafactura(Factura factura, Preventa preventa) {
       this.factura = factura;
       this.preventa = preventa;
    }
   
    public Integer getIdPreventaFactura() {
        return this.idPreventaFactura;
    }
    
    public void setIdPreventaFactura(Integer idPreventaFactura) {
        this.idPreventaFactura = idPreventaFactura;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Preventa getPreventa() {
        return this.preventa;
    }
    
    public void setPreventa(Preventa preventa) {
        this.preventa = preventa;
    }




}


