package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private Ciudad ciudad;
     private String nit;
     private String nombre;
     private String direccion;
     private String telefono;
     private String celular;
     private String correoElectronico;
     private String paginaWeb;
     private String rubro;
     private Set<Contacto> contactos = new HashSet<Contacto>(0);
     private Set<Cuentabancaria> cuentabancarias = new HashSet<Cuentabancaria>(0);
     private Set<Compra> compras = new HashSet<Compra>(0);

    public Proveedor() {
    }

	
    public Proveedor(Ciudad ciudad, String nombre, String direccion) {
        this.ciudad = ciudad;
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public Proveedor(Ciudad ciudad, String nit, String nombre, String direccion, String telefono, String celular, String correoElectronico, String paginaWeb, String rubro, Set<Contacto> contactos, Set<Cuentabancaria> cuentabancarias, Set<Compra> compras) {
       this.ciudad = ciudad;
       this.nit = nit;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.correoElectronico = correoElectronico;
       this.paginaWeb = paginaWeb;
       this.rubro = rubro;
       this.contactos = contactos;
       this.cuentabancarias = cuentabancarias;
       this.compras = compras;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }
    public String getRubro() {
        return this.rubro;
    }
    
    public void setRubro(String rubro) {
        this.rubro = rubro;
    }
    public Set<Contacto> getContactos() {
        return this.contactos;
    }
    
    public void setContactos(Set<Contacto> contactos) {
        this.contactos = contactos;
    }
    public Set<Cuentabancaria> getCuentabancarias() {
        return this.cuentabancarias;
    }
    
    public void setCuentabancarias(Set<Cuentabancaria> cuentabancarias) {
        this.cuentabancarias = cuentabancarias;
    }
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }




}


