package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Remito generated by hbm2java
 */
public class Remito  implements java.io.Serializable {


     private Integer numeroRemito;
     private Venta venta;
     private BigDecimal totalRemito;
     private Date fechaRemito;
     private String tipoRemito;
     private Date fechaRecepcion;
     private String nombreRecepcionista;

    public Remito() {
    }

	
    public Remito(Venta venta, BigDecimal totalRemito, Date fechaRemito, String tipoRemito) {
        this.venta = venta;
        this.totalRemito = totalRemito;
        this.fechaRemito = fechaRemito;
        this.tipoRemito = tipoRemito;
    }
    public Remito(Venta venta, BigDecimal totalRemito, Date fechaRemito, String tipoRemito, Date fechaRecepcion, String nombreRecepcionista) {
       this.venta = venta;
       this.totalRemito = totalRemito;
       this.fechaRemito = fechaRemito;
       this.tipoRemito = tipoRemito;
       this.fechaRecepcion = fechaRecepcion;
       this.nombreRecepcionista = nombreRecepcionista;
    }
   
    public Integer getNumeroRemito() {
        return this.numeroRemito;
    }
    
    public void setNumeroRemito(Integer numeroRemito) {
        this.numeroRemito = numeroRemito;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public BigDecimal getTotalRemito() {
        return this.totalRemito;
    }
    
    public void setTotalRemito(BigDecimal totalRemito) {
        this.totalRemito = totalRemito;
    }
    public Date getFechaRemito() {
        return this.fechaRemito;
    }
    
    public void setFechaRemito(Date fechaRemito) {
        this.fechaRemito = fechaRemito;
    }
    public String getTipoRemito() {
        return this.tipoRemito;
    }
    
    public void setTipoRemito(String tipoRemito) {
        this.tipoRemito = tipoRemito;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public String getNombreRecepcionista() {
        return this.nombreRecepcionista;
    }
    
    public void setNombreRecepcionista(String nombreRecepcionista) {
        this.nombreRecepcionista = nombreRecepcionista;
    }




}


