package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private Integer idSucursal;
     private String nombreSucursal;
     private String direccion;
     private String telefono;
     private Set<Almacen> almacens = new HashSet<Almacen>(0);
     private Set<Dosificacion> dosificacions = new HashSet<Dosificacion>(0);
     private Set<Ingreso> ingresos = new HashSet<Ingreso>(0);

    public Sucursal() {
    }

	
    public Sucursal(String nombreSucursal) {
        this.nombreSucursal = nombreSucursal;
    }
    public Sucursal(String nombreSucursal, String direccion, String telefono, Set<Almacen> almacens, Set<Dosificacion> dosificacions, Set<Ingreso> ingresos) {
       this.nombreSucursal = nombreSucursal;
       this.direccion = direccion;
       this.telefono = telefono;
       this.almacens = almacens;
       this.dosificacions = dosificacions;
       this.ingresos = ingresos;
    }
   
    public Integer getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(Integer idSucursal) {
        this.idSucursal = idSucursal;
    }
    public String getNombreSucursal() {
        return this.nombreSucursal;
    }
    
    public void setNombreSucursal(String nombreSucursal) {
        this.nombreSucursal = nombreSucursal;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Almacen> getAlmacens() {
        return this.almacens;
    }
    
    public void setAlmacens(Set<Almacen> almacens) {
        this.almacens = almacens;
    }
    public Set<Dosificacion> getDosificacions() {
        return this.dosificacions;
    }
    
    public void setDosificacions(Set<Dosificacion> dosificacions) {
        this.dosificacions = dosificacions;
    }
    public Set<Ingreso> getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Set<Ingreso> ingresos) {
        this.ingresos = ingresos;
    }




}


