package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopago generated by hbm2java
 */
public class Tipopago  implements java.io.Serializable {


     private Integer idTipopago;
     private String descPago;
     private Set<Venta> ventas = new HashSet<Venta>(0);
     private Set<Compra> compras = new HashSet<Compra>(0);
     private Set<Preventa> preventas = new HashSet<Preventa>(0);

    public Tipopago() {
    }

	
    public Tipopago(String descPago) {
        this.descPago = descPago;
    }
    public Tipopago(String descPago, Set<Venta> ventas, Set<Compra> compras, Set<Preventa> preventas) {
       this.descPago = descPago;
       this.ventas = ventas;
       this.compras = compras;
       this.preventas = preventas;
    }
   
    public Integer getIdTipopago() {
        return this.idTipopago;
    }
    
    public void setIdTipopago(Integer idTipopago) {
        this.idTipopago = idTipopago;
    }
    public String getDescPago() {
        return this.descPago;
    }
    
    public void setDescPago(String descPago) {
        this.descPago = descPago;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }
    public Set<Preventa> getPreventas() {
        return this.preventas;
    }
    
    public void setPreventas(Set<Preventa> preventas) {
        this.preventas = preventas;
    }




}


