package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tipocambio generated by hbm2java
 */
public class Tipocambio  implements java.io.Serializable {


     private Integer idTipoCambio;
     private Tipomoneda tipomoneda;
     private BigDecimal valor;

    public Tipocambio() {
    }

    public Tipocambio(Tipomoneda tipomoneda, BigDecimal valor) {
       this.tipomoneda = tipomoneda;
       this.valor = valor;
    }
   
    public Integer getIdTipoCambio() {
        return this.idTipoCambio;
    }
    
    public void setIdTipoCambio(Integer idTipoCambio) {
        this.idTipoCambio = idTipoCambio;
    }
    public Tipomoneda getTipomoneda() {
        return this.tipomoneda;
    }
    
    public void setTipomoneda(Tipomoneda tipomoneda) {
        this.tipomoneda = tipomoneda;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


