package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipomoneda generated by hbm2java
 */
public class Tipomoneda  implements java.io.Serializable {


     private Integer idTipomoneda;
     private String descripcion;
     private Set<Tipocambio> tipocambios = new HashSet<Tipocambio>(0);
     private Set<Venta> ventas = new HashSet<Venta>(0);
     private Set<Compra> compras = new HashSet<Compra>(0);
     private Set<Preventa> preventas = new HashSet<Preventa>(0);
     private Set<Cuentabancaria> cuentabancarias = new HashSet<Cuentabancaria>(0);

    public Tipomoneda() {
    }

	
    public Tipomoneda(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tipomoneda(String descripcion, Set<Tipocambio> tipocambios, Set<Venta> ventas, Set<Compra> compras, Set<Preventa> preventas, Set<Cuentabancaria> cuentabancarias) {
       this.descripcion = descripcion;
       this.tipocambios = tipocambios;
       this.ventas = ventas;
       this.compras = compras;
       this.preventas = preventas;
       this.cuentabancarias = cuentabancarias;
    }
   
    public Integer getIdTipomoneda() {
        return this.idTipomoneda;
    }
    
    public void setIdTipomoneda(Integer idTipomoneda) {
        this.idTipomoneda = idTipomoneda;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Tipocambio> getTipocambios() {
        return this.tipocambios;
    }
    
    public void setTipocambios(Set<Tipocambio> tipocambios) {
        this.tipocambios = tipocambios;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }
    public Set<Preventa> getPreventas() {
        return this.preventas;
    }
    
    public void setPreventas(Set<Preventa> preventas) {
        this.preventas = preventas;
    }
    public Set<Cuentabancaria> getCuentabancarias() {
        return this.cuentabancarias;
    }
    
    public void setCuentabancarias(Set<Cuentabancaria> cuentabancarias) {
        this.cuentabancarias = cuentabancarias;
    }




}


