package sys.model;
// Generated 21-jul-2016 11:11:08 by Hibernate Tools 4.3.1



/**
 * Ventafactura generated by hbm2java
 */
public class Ventafactura  implements java.io.Serializable {


     private Integer idVentaFactura;
     private Factura factura;
     private Venta venta;

    public Ventafactura() {
    }

    public Ventafactura(Factura factura, Venta venta) {
       this.factura = factura;
       this.venta = venta;
    }
   
    public Integer getIdVentaFactura() {
        return this.idVentaFactura;
    }
    
    public void setIdVentaFactura(Integer idVentaFactura) {
        this.idVentaFactura = idVentaFactura;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }




}


